name: Auto_Crawl_Data

on:
  schedule:
    - cron: '0 0 * * *' # 每天台灣時間早上 8 點自動跑
  workflow_dispatch: # 讓你可以隨時手動點按鈕跑一次

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝套件
        run: pip install requests beautifulsoup4

      - name: 執行爬蟲
        run: python main.py

      - name: 自動提交檔案回 GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add data/*
          git commit -m "Update: $(date +'%Y-%m-%d') market data" || echo "No changes to commit"
          git push